main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('result/', views.result, name='result'),
    path('result/<str:task_id>/', views.result_details, name='result_details'),
    path('status/', views.status, name='status'),
    path('submit-1/', views.submit_1, name='submit_1'),
    path('submit-2/', views.submit_2, name='submit_2'),
    path('submit-3/', views.submit_3, name='submit_3'),
    path('api/get_task_result_by_id/<str:task_id>/', views.api_get_task_result_by_id, name='api_get_task_result_by_id'),
]

webapp/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models


class TaskResult(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('running', 'Running'),
        ('done', 'Done'),
        ('failed', 'Failed'),
    ]

    TASK_NAME_CHOICES = [
        ('task_1', 'Task 1'),
        ('task_2', 'Task 2'),
        ('task_3', 'Task 3'),
        ('unknown_task', 'Unknown Task'),
    ]

    task_id = models.CharField(max_length=64, unique=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    # no need to set blank=True when handling the POST request manually
    # set null=True to allow this field to be NULL in the database 
    # null=False is the default value, in this case, default is required
    result = models.JSONField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    # the handler could handle multiple tasks
    # one task_name corresponds to one function handling this task
    task_name = models.CharField(choices=TASK_NAME_CHOICES, default='unknown-task')
    task_arg = models.JSONField(null=True)

main/views.py
from django.shortcuts import render
from django.http import HttpRequest, JsonResponse, HttpResponseRedirect
from django.urls import reverse
from uuid import uuid4

from .models import TaskResult
from .management.commands.runtaskhandler import MAX_CONCURRENT_TASKS

import json


def home(request):
    return render(request, 'main/home.html', {'navbar_select': 'home'})

def result(request: HttpRequest):
    if request.method == 'POST':
        task_id = request.POST.get('taskId', None)
        return HttpResponseRedirect(reverse('main:result_details', args=(task_id,)))
    else:
        return render(request, 'main/result.html', {'navbar_select': 'result'})

def result_details(request: HttpRequest, task_id: str):
    task = TaskResult.objects.get(task_id=task_id)
    return render(request, 'main/result-details.html', {
        'navbar_select': 'result', 
        'task_id': task.task_id,
        'created_at': task.created_at,
        'status': task.status
    })

def status(request):
    return render(request, 'main/status.html', {'navbar_select': 'status'})

def submit_1(request: HttpRequest):
    if request.method == 'POST':
        field1 = request.POST.get('field1', None)
        field2 = request.POST.get('field2', None)
        task = TaskResult()
        task.task_id = str(uuid4())
        task.task_name = 'task_1'
        task.task_arg = {'field1': field1, 'field2': field2}
        task.save()
        return HttpResponseRedirect(reverse('main:result_details', args=(task.task_id,)))
    else:
        return render(request, 'main/submit-1.html', {'navbar_select': 'submit'})

def submit_2(request):
    return render(request, 'main/submit-2.html', {'navbar_select': 'submit'})

def submit_3(request):
    return render(request, 'main/submit-3.html', {'navbar_select': 'submit'})

def api_get_task_result_by_id(request: HttpRequest, task_id: str):
    task = TaskResult.objects.get(task_id=task_id)
    return JsonResponse({'result': json.dumps(task.result), 'status': task.status})

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'main/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/main.css' %}" rel="stylesheet">
    <script src="{% static 'main/bootstrap/dist/js/bootstrap.bundle.min.js' %}" defer></script>
    <script src="{% static 'main/main.js' %}" defer></script>
    {% block otherscripts %}{% endblock %}
    <title>Web App</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md bg-body-secondary">
        <div class="container-fluid my-1">
            <div class="navbar-brand mx-5"><b>Navbar</b></div>
            <!--toggler for menu items when the width is small-->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item me-3">
                        <a class="nav-link{% if navbar_select == 'home' %} active my-active{% endif %}" href="{% url 'main:home' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown me-3">
                        <a class="nav-link dropdown-toggle{% if navbar_select == 'submit' %} active my-active{% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Submit
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'main:submit_1' %}">Submit Task 1</a></li>
                            <li><a class="dropdown-item" href="{% url 'main:submit_2' %}">Submit Task 2</a></li>
                            <li><a class="dropdown-item" href="{% url 'main:submit_3' %}">Submit Task 3</a></li>
                        </ul>
                    </li>
                    <li class="nav-item me-3">
                        <a class="nav-link{% if navbar_select == 'result' %} active my-active{% endif %}" href="{% url 'main:result' %}">Result</a>
                    </li>
                    <li class="nav-item me-3">
                        <a class="nav-link{% if navbar_select == 'status' %} active my-active{% endif %}" href="{% url 'main:status' %}">Status</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <main class="container my-5" style="height: 70vh;">
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <div class="container text-center">&copy; 2025 Authors. All rights reserved.</div>
    </footer>
  </body>
</html>

main/templates/main/home.html
{% extends "main/base.html" %}

{% block content %}
<div class="row" style="height: 100%;">
  <div class="col-4 text-center" style="height: 100%;">
    <div class="card" style="height: 100%;">
      <div class="card-body">
        <h2 class="card-title">Submit Task 1</h2>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="{% url 'main:submit_1' %}" class="btn btn-primary">Submit Task 1</a>
      </div>
    </div>
  </div>
  <div class="col-4 text-center" style="height: 100%;">
    <div class="card" style="height: 100%;">
      <div class="card-body">
        <h2 class="card-title">Submit Task 2</h2>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="{% url 'main:submit_2' %}" class="btn btn-primary">Submit Task 2</a>
      </div>
    </div>
  </div>
  <div class="col-4 text-center" style="height: 100%;">
    <div class="card" style="height: 100%;">
      <div class="card-body">
        <h2 class="card-title">Submit Task 3</h2>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="{% url 'main:submit_3' %}" class="btn btn-primary">Submit Task 3</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/result-details.html
{% extends "main/base.html" %}

{% load static %}

{% block otherscripts %}
<script src="{% static 'main/resultDetails.js' %}" defer></script>
{% endblock %}

{% block content %}
<h2 class="text-center">Task Information</h2>
<hr>
<div class="d-flex justify-content-center">
    <ul class="list-group list-group-horizontal">
        <li class="list-group-item">
            <div>
                <div class="fw-bold">Task ID</div>
                <div>{{ task_id }}</div>
            </div>
        </li>
        <li class="list-group-item">
            <div>
                <div class="fw-bold">Status</div>
                <div id="taskStatus">{{ status }}</div>
            </div>
        </li>
    </ul>
</div>


<h2 class="text-center mt-5">Task Result</h2>
<hr>
<div>
    <div>Task result</div>
    <div id="taskResult" data-task-id="{{ task_id }}">Please wait</div>
</div>
{% endblock %}

main/templates/main/result.html
{% extends "main/base.html" %}

{% block content %}
<div class="d-flex justify-content-center align-items-center" style="height: 100%;">
    <div style="width: 80%; padding-bottom: 20%;">
        <h2 class="text-center mb-5">Search Task Result</h2>
        <form action="{% url 'main:result' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-8 offset-2">
                    <input type="text" class="form-control" id="taskId" name="taskId" placeholder="Task ID">
                </div>
                <div class="col-2">
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/main/status.html
{% extends "main/base.html" %}

{% block content %}
<h1>This is status.html</h1>
{% endblock %}

main/templates/main/submit-1.html
{% extends "main/base.html" %}

{% load static %}

{% block otherscripts %}
<script src="{% static 'main/submit1.js' %}" defer></script>
{% endblock %}

{% block content %}
<div class="mx-5">
    <h1>Submit Task 1</h1>

    <form class="row mt-5 mx-5 g-3" action="{% url 'main:submit_1' %}" method="post">
        {% csrf_token %}
        <div class="col-6">
            <label for="field1" class="form-label">Field 1</label>
            <input type="text" class="form-control" id="field1" name="field1" placeholder="Placeholder for Field 1">
            <div id="field1Feedback" class="invisible">
                Placeholder
            </div>
        </div>
        <div class="col-6">
            <label for="field2" class="form-label">Field 2</label>
            <input type="text" class="form-control" id="field2" name="field2" placeholder="Placeholder for Field 2">
            <div id="field2Feedback" class="invisible">
                Placeholder
            </div>
        </div>
        <div class="col-12 mt-5">
            <button type="submit" class="btn btn-primary" id="submitButton" disabled>Submit</button>
        </div>
    </form>
</div>

{% endblock %}

main/templates/main/submit-2.html
{% extends "main/base.html" %}

{% block content %}
<h1>This is submit-2.html</h1>
{% endblock %}

main/templates/main/submit-3.html
{% extends "main/base.html" %}

{% block content %}
<h1>This is submit-3.html</h1>
{% endblock %}